version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set root password
      MYSQL_DATABASE: booking_management  # Create database
    ports:
      - "3309:3306"  # Map MySQL container port 3306 to host port 3309
    networks:
      - app-network

  spring-app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - mysql-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/booking_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"  # Map Spring Boot app port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
